### ISSUE TITLE
comoser 错误，能否更新依赖包

### ISSUE THREAD

**Issue by liuyami** [edk24/ant-cloudpay-sdk#1]
Problem 1
    - Root composer.json requires yuxiaobo/ant-cloudpay-sdk * -> satisfiable by yuxiaobo/ant-cloudpay-sdk[0.0.1, 0.0.2, 1.0.0].
    - yuxiaobo/ant-cloudpay-sdk[0.0.1, ..., 0.0.2, 1.0.0] require guzzlehttp/guzzle ~6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.8] but it conflicts with your
 root composer.json require (^7.2).

---

能否留个V，有些问题想请教一下

**Comment by edk24** [comment]
更新了一个 `1.0.1` 的版本， 优化了 php 和 guzzle 包的宽容度，感谢您的反馈
